SET NAMES UTF8;
DROP DATABASE IF EXISTS wxjnr;
CREATE DATABASE wxjnr CHARSET=UTF8;
USE wxjnr;
/*创建飞车头部表*/
CREATE TABLE jnr_nr(
	id INT PRIMARY KEY AUTO_INCREMENT,
	div_1 VARCHAR(255),
	div_2 VARCHAR(255)
);
/*插入首页sp图片*/
INSERT INTO jnr_nr VALUES(NULL,'离上次见面已经',"2018-03-19");
INSERT INTO jnr_nr VALUES(NULL,'距离TA生日还有',"2018-03-22");